const googleNews = (query) =>
  `https://news.google.com/rss/search?q=${query}&hl=en-US&gl=US&ceid=US:en`;

export const NEWS_SOURCES = Object.freeze([
  {
    id: 'coindesk',
    url: 'https://www.coindesk.com/arc/outboundfeeds/rss/',
    source: 'CoinDesk',
    format: 'rss',
    topic: 'general',
    sourceTier: 'editorial',
    maxItems: 12,
    maxAgeHours: 72,
    timeoutMs: 6500,
  },
  {
    id: 'blockworks',
    url: 'https://blockworks.co/feed/',
    source: 'Blockworks',
    format: 'atom',
    topic: 'general',
    sourceTier: 'editorial',
    maxItems: 12,
    maxAgeHours: 72,
    timeoutMs: 6500,
  },
  {
    id: 'the-block',
    url: 'https://theblock.co/rss.xml',
    source: 'The Block',
    format: 'rss',
    topic: 'general',
    sourceTier: 'editorial',
    maxItems: 12,
    maxAgeHours: 72,
    timeoutMs: 6500,
  },
  {
    id: 'decrypt',
    url: 'https://decrypt.co/feed',
    source: 'Decrypt',
    format: 'rss',
    topic: 'general',
    sourceTier: 'editorial',
    maxItems: 12,
    maxAgeHours: 72,
    timeoutMs: 6500,
  },
  {
    id: 'google-news-eth',
    url: googleNews('%28Ethereum%20OR%20ETH%20OR%20staking%20OR%20rsETH%29%20crypto%20when%3A7d'),
    source: 'Google News ETH',
    format: 'rss',
    topic: 'eth',
    sourceTier: 'discovery',
    maxItems: 16,
    maxAgeHours: 168,
    timeoutMs: 6500,
  },
  {
    id: 'google-news-link',
    url: googleNews('%28Chainlink%20OR%20%22LINK%22%20OR%20CCIP%29%20crypto%20when%3A7d'),
    source: 'Google News LINK',
    format: 'rss',
    topic: 'link',
    sourceTier: 'discovery',
    maxItems: 16,
    maxAgeHours: 168,
    timeoutMs: 6500,
  },
  {
    id: 'dow-jones-markets',
    url: 'https://feeds.content.dowjones.io/public/rss/RSSMarketsMain',
    source: 'Dow Jones Markets',
    format: 'rss',
    topic: 'macro',
    sourceTier: 'macro',
    maxItems: 10,
    maxAgeHours: 72,
    timeoutMs: 6500,
  },
  {
    id: 'ft-markets',
    url: 'https://www.ft.com/markets?format=rss',
    source: 'FT Markets',
    format: 'rss',
    topic: 'macro',
    sourceTier: 'macro',
    maxItems: 10,
    maxAgeHours: 72,
    timeoutMs: 6500,
  },
]);
